/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.Clientes;
import Errores.Lectura;
import dao.DaoCliente;
import javax.swing.JOptionPane;

/**
 *
 * @author angel
 */
public class Crearcuenta extends javax.swing.JDialog {

    DaoCliente dao = new DaoCliente();

    public Crearcuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajaTexto = new javax.swing.JTextField();
        DireccionCajaTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoCajaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdadeCajaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CorreoCajaTexto = new javax.swing.JTextField();
        ContraseñaCajaTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Boton_guardar = new javax.swing.JButton();
        BoxGenero = new javax.swing.JComboBox<>();
        Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 54, -1));

        NombreCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(NombreCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 165, -1));

        DireccionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(DireccionCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 165, -1));

        jLabel2.setText("Direeccion");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 70, -1));

        TelefonoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(TelefonoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 165, -1));

        jLabel3.setText("Telefono");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 54, -1));

        EdadeCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadeCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(EdadeCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 165, -1));

        jLabel5.setText("Genero");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 54, -1));

        jLabel6.setText("Edad");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 54, -1));

        jLabel7.setText("Contraseña");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 70, -1));

        CorreoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(CorreoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 165, -1));

        ContraseñaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(ContraseñaCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 165, -1));

        jLabel8.setText("Correo");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 54, -1));

        Boton_guardar.setText("Crear cuenta");
        Boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardarActionPerformed(evt);
            }
        });
        jPanel8.add(Boton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, -1));

        BoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jPanel8.add(BoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));
        jPanel8.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 160, 20));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCajaTextoActionPerformed

    private void DireccionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionCajaTextoActionPerformed

    private void TelefonoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoCajaTextoActionPerformed

    private void CorreoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoCajaTextoActionPerformed

    private void ContraseñaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaCajaTextoActionPerformed

    private void Boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardarActionPerformed
        int a = Lectura.Ltext(NombreCajaTexto.getText())
                + Lectura.Lint(EdadeCajaTexto.getText())
                + Lectura.Ltext(DireccionCajaTexto.getText())
                + Lectura.Ltelefono(TelefonoCajaTexto.getText())
                + Lectura.Lcorreo(CorreoCajaTexto.getText(), "+(gmail)+")
                + Lectura.LContraseña(ContraseñaCajaTexto.getText());

        if (a == 6) {
            dao.createCliente(new Clientes(1,
                    NombreCajaTexto.getText(),
                    Integer.valueOf(EdadeCajaTexto.getText()),
                    DireccionCajaTexto.getText(),
                    String.valueOf(BoxGenero.getSelectedItem()),
                    TelefonoCajaTexto.getText(),
                    CorreoCajaTexto.getText(),
                    ContraseñaCajaTexto.getText()));
            LimpiarCajas();
            Error.setText("");
            JOptionPane.showMessageDialog(null, "Se a creado el cliente correctamente");
            this.dispose();
        } else {
            Error.setText("hay un error en la sintaxis");
            
        }


    }//GEN-LAST:event_Boton_guardarActionPerformed

    private void EdadeCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadeCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadeCajaTextoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_guardar;
    private javax.swing.JComboBox<String> BoxGenero;
    private javax.swing.JTextField ContraseñaCajaTexto;
    private javax.swing.JTextField CorreoCajaTexto;
    private javax.swing.JTextField DireccionCajaTexto;
    private javax.swing.JTextField EdadeCajaTexto;
    private javax.swing.JLabel Error;
    private javax.swing.JTextField NombreCajaTexto;
    private javax.swing.JTextField TelefonoCajaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
private void LimpiarCajas() {
        NombreCajaTexto.setText("");
        EdadeCajaTexto.setText("");
        DireccionCajaTexto.setText("");
        TelefonoCajaTexto.setText("");
        CorreoCajaTexto.setText("");
        ContraseñaCajaTexto.setText("");
    }

}
