/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.Clientes;
import Errores.Lectura;
import dao.DaoCliente;
import javax.swing.JOptionPane;

public class EditarPerfil extends javax.swing.JDialog {

    DaoCliente dao = new DaoCliente();
    private int id = Tienda.Id;
    public EditarPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AsignarUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajaTexto = new javax.swing.JTextField();
        DireccionCajaTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoCajaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdadeCajaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ContraseñaCajaTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Error7 = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        Error5 = new javax.swing.JLabel();
        BoxGenero = new javax.swing.JComboBox<>();
        Correo_Caja_De_texto = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setText("Nombre");

        NombreCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCajaTextoActionPerformed(evt);
            }
        });
        NombreCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreCajaTextoKeyTyped(evt);
            }
        });

        DireccionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionCajaTextoActionPerformed(evt);
            }
        });
        DireccionCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionCajaTextoKeyTyped(evt);
            }
        });

        jLabel2.setText("Direeccion");

        TelefonoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoCajaTextoActionPerformed(evt);
            }
        });
        TelefonoCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoCajaTextoKeyTyped(evt);
            }
        });

        jLabel3.setText("Telefono");

        EdadeCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadeCajaTextoActionPerformed(evt);
            }
        });
        EdadeCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadeCajaTextoKeyTyped(evt);
            }
        });

        jLabel5.setText("Genero");

        jLabel6.setText("Edad");

        jLabel7.setText("Contraseña");

        ContraseñaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaCajaTextoActionPerformed(evt);
            }
        });

        jLabel8.setText("Correo");

        Error7.setText("jLabel9");

        Error1.setText("jLabel9");

        Error2.setText("jLabel9");

        Error3.setText("jLabel9");

        Error5.setText("jLabel9");

        BoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        Correo_Caja_De_texto.setText("Correo");

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Error3))
                            .addComponent(TelefonoCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Error5))
                            .addComponent(EdadeCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(Error2))
                            .addComponent(DireccionCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Error1))
                            .addComponent(NombreCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Correo_Caja_De_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(Error7))
                            .addComponent(ContraseñaCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButton5)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Error1))
                .addComponent(NombreCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Error2))
                .addGap(4, 4, 4)
                .addComponent(DireccionCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Error5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(EdadeCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addComponent(BoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(Error3))
                .addGap(4, 4, 4)
                .addComponent(TelefonoCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addComponent(Correo_Caja_De_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Error7)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContraseñaCajaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCajaTextoActionPerformed

    private void DireccionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionCajaTextoActionPerformed

    private void TelefonoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoCajaTextoActionPerformed

    private void EdadeCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadeCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadeCajaTextoActionPerformed

    private void ContraseñaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaCajaTextoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        

            int a = Lectura.Ltext(NombreCajaTexto.getText())
                    + Lectura.Lint(EdadeCajaTexto.getText())
                    + Lectura.Ltext(DireccionCajaTexto.getText())
                    + Lectura.Ltelefono(TelefonoCajaTexto.getText())                  
                    + Lectura.LContraseña(ContraseñaCajaTexto.getText());

            if (a == 5) {
                Clientes b = new Clientes(1,
                        NombreCajaTexto.getText(),
                        Integer.valueOf(EdadeCajaTexto.getText()),
                        DireccionCajaTexto.getText(),
                        String.valueOf(BoxGenero.getSelectedItem()),
                        TelefonoCajaTexto.getText(),
                        Correo_Caja_De_texto.getText(),
                        ContraseñaCajaTexto.getText());
                dao.updateCliente(b, String.valueOf(id));
                LimpiarCajas();
                JOptionPane.showMessageDialog(null, "Se a editado su usuario");
                this.dispose();
            } else {
                if (Lectura.Ltext(NombreCajaTexto.getText()) != 1) {
                    Error1.setText("!");
                } else {
                    Error1.setText("");
                }
                if (Lectura.Ltext(DireccionCajaTexto.getText()) != 1) {
                    Error2.setText("!");
                } else {
                    Error2.setText("");
                }
                if (Lectura.Ltelefono(TelefonoCajaTexto.getText()) != 1) {
                    Error3.setText("!");
                } else {
                    Error3.setText("");
                }
                if (Lectura.Lint(EdadeCajaTexto.getText()) != 1) {
                    Error5.setText("!");
                } else {
                    Error5.setText("");
                }
                if (Lectura.LContraseña(ContraseñaCajaTexto.getText()) != 1) {
                    Error7.setText("!");
                } else {
                    Error7.setText("");
                }
            }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void NombreCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreCajaTextoKeyTyped
        if (NombreCajaTexto.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreCajaTextoKeyTyped

    private void DireccionCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionCajaTextoKeyTyped
        if (DireccionCajaTexto.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_DireccionCajaTextoKeyTyped

    private void EdadeCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadeCajaTextoKeyTyped
        if (EdadeCajaTexto.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_EdadeCajaTextoKeyTyped

    private void TelefonoCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoKeyTyped
        if (TelefonoCajaTexto.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoCajaTextoKeyTyped

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxGenero;
    private javax.swing.JTextField ContraseñaCajaTexto;
    private javax.swing.JLabel Correo_Caja_De_texto;
    private javax.swing.JTextField DireccionCajaTexto;
    private javax.swing.JTextField EdadeCajaTexto;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JLabel Error5;
    private javax.swing.JLabel Error7;
    private javax.swing.JTextField NombreCajaTexto;
    private javax.swing.JTextField TelefonoCajaTexto;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
private void LimpiarCajas() {
        NombreCajaTexto.setText("");
        EdadeCajaTexto.setText("");
        DireccionCajaTexto.setText("");
        TelefonoCajaTexto.setText("");
        ContraseñaCajaTexto.setText("");
    }

private void AsignarUsuario() {
        Clientes c =  dao.readCliente(String.valueOf(id));
    
        NombreCajaTexto.setText(c.getNombre());
        EdadeCajaTexto.setText(String.valueOf(c.getEdad()));
        DireccionCajaTexto.setText(c.getDireccion());
        Correo_Caja_De_texto.setText(c.getCorreo());
        TelefonoCajaTexto.setText(String.valueOf(c.getTelefono()));
        ContraseñaCajaTexto.setText(c.getContraseña());
        BoxGenero.setSelectedItem(c.getGenero());
        
    }

}
