/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Ventanas;

import Clases.Administrador;
import Clases.Clientes;
import Clases.Empleados;
import Errores.Lectura;
import dao.DaoAdministrador;
import dao.DaoCliente;
import dao.DaoEmpleados;
import javax.swing.JFrame;

/**
 *
 * @author PC
 */
public class InicioSesion extends javax.swing.JDialog {

    DaoCliente dao = new DaoCliente();
    DaoAdministrador daoA = new DaoAdministrador();
    DaoEmpleados daoE = new DaoEmpleados();

    public InicioSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CorreoTXT1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ContraseñaTxT1 = new javax.swing.JTextField();
        IniciodeS1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(237, 237, 237));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Correo");

        CorreoTXT1.setBackground(new java.awt.Color(204, 204, 204));
        CorreoTXT1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CorreoTXT1.setForeground(new java.awt.Color(0, 0, 0));
        CorreoTXT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTXT1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");

        ContraseñaTxT1.setBackground(new java.awt.Color(204, 204, 204));
        ContraseñaTxT1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ContraseñaTxT1.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaTxT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaTxT1ActionPerformed(evt);
            }
        });

        IniciodeS1.setText("Iniciar sesion");
        IniciodeS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciodeS1ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Usuario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoTXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel4))
                            .addComponent(ContraseñaTxT1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(IniciodeS1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel3)))
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(CorreoTXT1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(ContraseñaTxT1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Error, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciodeS1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CorreoTXT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoTXT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoTXT1ActionPerformed

    private void ContraseñaTxT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaTxT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaTxT1ActionPerformed

    private void IniciodeS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciodeS1ActionPerformed
        int e = +Lectura.Lcorreo(CorreoTXT1.getText(), "+(gmail)+")
                + Lectura.Lcorreo(CorreoTXT1.getText(), "+(admin)+")
                + Lectura.Lcorreo(CorreoTXT1.getText(), "+(empleado)+")
                + Lectura.LContraseña(ContraseñaTxT1.getText());

        if (e == 2) {
            int admin, empleado, usuario;
            admin = Lectura.Lcorreo(CorreoTXT1.getText(), "+(admin)+");
            empleado = Lectura.Lcorreo(CorreoTXT1.getText(), "+(empleado)+");
            usuario = Lectura.Lcorreo(CorreoTXT1.getText(), "+(gmail)+");
            if (admin == 1) {
                SesionAdmin();
            }
            if (empleado == 1) {
                SesionEmpleado();
            }
            if (usuario == 1) {
                SesionUsuario();
            }

        } else {
            Error.setText("Ingrese valores validos");
        }


    }//GEN-LAST:event_IniciodeS1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Crearcuenta crear = new Crearcuenta(new JFrame(), true);
        crear.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContraseñaTxT1;
    private javax.swing.JTextField CorreoTXT1;
    private javax.swing.JLabel Error;
    private javax.swing.JButton IniciodeS1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
private void SesionUsuario() {
        Clientes a = dao.readClienteCorreo(CorreoTXT1.getText());
        if (a == null) {
            Error.setText("No se encontro la cuenta");
        } else {
            if (a.getContraseña().equals(ContraseñaTxT1.getText())) {
                Tienda.Nombre = a.getNombre();
                Tienda.Id = a.getId();
                Tienda.NombreUsuario.setText(a.getNombre() + " id: " + Tienda.Id);
                Tienda.TipoUsuario = "cliente";
                Error.setText("");
                this.dispose();
            } else {
                Error.setText("La Contraseña es incorrecta");
            }
        }
    }

    private void SesionAdmin() {
        Administrador a = daoA.readAdministradorCorreo(CorreoTXT1.getText());
        if (a == null) {
            Error.setText("No se encontro la cuenta");
        } else {
            if (a.getContraseña().equals(ContraseñaTxT1.getText())) {
//                    Productos_Administracion pa = new Productos_Administracion();
//                    pa.setVisible(true);
                Tienda.Nombre = a.getNombre();
                Tienda.Id = a.getId();
                Tienda.NombreUsuario.setText(a.getNombre() + " id: " + Tienda.Id);
                Tienda.TipoUsuario = "admin";
                Error.setText("");
                this.dispose();
            } else {
                Error.setText("La Contraseña es incorrecta");
            }
        }
    }

    private void SesionEmpleado() {
        Empleados a = daoE.readEmpleadosCorreo(CorreoTXT1.getText());
        if (a == null) {
            Error.setText("No se encontro la cuenta");
        } else {
            if (a.getContraseña().equals(ContraseñaTxT1.getText())) {
//                    Productos_Administracion pa = new Productos_Administracion();
//                    pa.Panelprincipal.remove(0);//admin
//                    pa.Panelprincipal.remove(1);//clientes
//                    pa.Panelprincipal.remove(2);//Empleados
//                    pa.setVisible(true);
                Tienda.Nombre = a.getNombre();
                Tienda.Id = a.getId();
                Tienda.NombreUsuario.setText(a.getNombre() + " id: " + Tienda.Id);
                Tienda.TipoUsuario = "empleado";
                Error.setText("");
                this.dispose();

            } else {
                Error.setText("La Contraseña es incorrecta");
            }
        }
    }

}
