/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;
import Clases.Clientes;
import dao.DaoCliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


public class PanelClientes extends javax.swing.JPanel {
    DaoCliente dao = new DaoCliente();
    public PanelClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajaTexto = new javax.swing.JTextField();
        DireccionCajaTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoCajaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdadeCajaTexto = new javax.swing.JTextField();
        GeneroCajaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CorreoCajaTexto = new javax.swing.JTextField();
        ContraseñaCajaTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Boton_guardar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablareportes = new javax.swing.JTable();
        IdLeavel = new javax.swing.JLabel();
        IdCajaTexto = new javax.swing.JTextField();
        Boton_Buscar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 54, -1));

        NombreCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(NombreCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 165, -1));

        DireccionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(DireccionCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 165, -1));

        jLabel2.setText("Direeccion");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 104, 70, -1));

        TelefonoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(TelefonoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 165, -1));

        jLabel3.setText("Telefono");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 54, -1));

        EdadeCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadeCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(EdadeCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 78, 165, -1));

        GeneroCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(GeneroCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 130, 165, -1));

        jLabel5.setText("Genero");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 108, 54, -1));

        jLabel6.setText("Edad");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 56, 54, -1));

        jLabel7.setText("Contraseña");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 208, 70, -1));

        CorreoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(CorreoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 165, -1));

        ContraseñaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(ContraseñaCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 165, -1));

        jLabel8.setText("Correo");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 208, 54, -1));

        Boton_guardar.setText("Guardar");
        Boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardarActionPerformed(evt);
            }
        });
        jPanel8.add(Boton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jPanel8.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablareportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Edad", "Direccion", "Genero", "Telefono", "Correo", "Contraseña"
            }
        ));
        Tablareportes.setEnabled(false);
        Tablareportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablareportesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablareportes);
        ActualisarTabla();

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 180));

        IdLeavel.setText("Id");
        jPanel2.add(IdLeavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        IdCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCajaTextoActionPerformed(evt);
            }
        });
        jPanel2.add(IdCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

        Boton_Buscar.setText("Buscar");
        Boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Boton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 770, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCajaTextoActionPerformed

    private void DireccionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionCajaTextoActionPerformed

    private void TelefonoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoCajaTextoActionPerformed

    private void EdadeCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadeCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadeCajaTextoActionPerformed

    private void GeneroCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroCajaTextoActionPerformed

    private void CorreoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoCajaTextoActionPerformed

    private void ContraseñaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaCajaTextoActionPerformed

    private void Boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardarActionPerformed
        dao.createCliente(new Clientes(1,
            NombreCajaTexto.getText(),
            Integer.valueOf(EdadeCajaTexto.getText()),
            DireccionCajaTexto.getText(),
            GeneroCajaTexto.getText(),
            TelefonoCajaTexto.getText(),
            CorreoCajaTexto.getText(),
            ContraseñaCajaTexto.getText()));

    LimpiarCajas();
    ActualisarTabla();
    }//GEN-LAST:event_Boton_guardarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        LimpiarCajas();
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dao.deleteCliente(IdCajaTexto.getText());
        ActualisarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Clientes b = new Clientes(1,
            NombreCajaTexto.getText(),
            Integer.valueOf(EdadeCajaTexto.getText()),
            DireccionCajaTexto.getText(),
            GeneroCajaTexto.getText(),
            TelefonoCajaTexto.getText(),
            CorreoCajaTexto.getText(),
            ContraseñaCajaTexto.getText());
        dao.updateCliente(b, IdCajaTexto.getText());
        LimpiarCajas();
        ActualisarTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TablareportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablareportesMouseClicked
        int filaSeleccionada = Tablareportes.rowAtPoint(evt.getPoint());
        IdCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 0).toString());
        NombreCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 1).toString());
        EdadeCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 2).toString());
        DireccionCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 3).toString());
        GeneroCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 4).toString());
        TelefonoCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 5).toString());
        CorreoCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 6).toString());
        ContraseñaCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 7).toString());
    }//GEN-LAST:event_TablareportesMouseClicked

    private void IdCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCajaTextoActionPerformed

    private void Boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarActionPerformed
        Clientes cliente = dao.readCliente(IdCajaTexto.getText());
        if (cliente == null) {
            System.out.println("la id no existe");

        }else{

            NombreCajaTexto.setText(cliente.getNombre());
            EdadeCajaTexto.setText(String.valueOf(cliente.getEdad()));
            DireccionCajaTexto.setText(cliente.getDireccion());
            GeneroCajaTexto.setText(cliente.getGenero());
            TelefonoCajaTexto.setText(cliente.getTelefono());
            CorreoCajaTexto.setText(cliente.getCorreo());
            ContraseñaCajaTexto.setText(cliente.getContraseña());

        }
    }//GEN-LAST:event_Boton_BuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Buscar;
    private javax.swing.JButton Boton_guardar;
    private javax.swing.JTextField ContraseñaCajaTexto;
    private javax.swing.JTextField CorreoCajaTexto;
    private javax.swing.JTextField DireccionCajaTexto;
    private javax.swing.JTextField EdadeCajaTexto;
    private javax.swing.JTextField GeneroCajaTexto;
    private javax.swing.JTextField IdCajaTexto;
    private javax.swing.JLabel IdLeavel;
    private javax.swing.JTextField NombreCajaTexto;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTable Tablareportes;
    private javax.swing.JTextField TelefonoCajaTexto;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void ActualisarTabla(){
            
        
            ArrayList<Clientes> clientes = dao.readClientes();
        
        
        DefaultTableModel m;
        m =(DefaultTableModel)Tablareportes.getModel();
        while(m.getRowCount()>0){
            m.removeRow(0);
        
        }
        Object[] rowData = new Object[9];
        for(int i = 0; i< clientes.size();i++){
                rowData[0] = clientes.get(i).getId();
                rowData[1] = clientes.get(i).getNombre();
                rowData[2] = clientes.get(i).getEdad();
                rowData[3] = clientes.get(i).getDireccion();
                rowData[4] = clientes.get(i).getGenero();
                rowData[5] = clientes.get(i).getTelefono(); 
                rowData[6] = clientes.get(i).getCorreo();
                rowData[7] = clientes.get(i).getContraseña();
               m.addRow(rowData);    
        }
        Tablareportes.setModel(m);
    }
    
    
    private void LimpiarCajas(){
        NombreCajaTexto.setText("");
        EdadeCajaTexto.setText("");
        DireccionCajaTexto.setText("");
        GeneroCajaTexto.setText("");
        TelefonoCajaTexto.setText("");
        CorreoCajaTexto.setText("");
        ContraseñaCajaTexto.setText("");
        IdCajaTexto.setText("");
         
        
    }

}
