/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Clases.Administrador;
import Errores.Lectura;
import dao.DaoAdministrador;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Panel_Administradores extends javax.swing.JPanel {

    DaoAdministrador dao = new DaoAdministrador();

    /**
     * Creates new form Panel_Administradores
     */
    public Panel_Administradores() {
        initComponents();
        LimpiarError();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajaTexto = new javax.swing.JTextField();
        DireccionCajaTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoCajaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EdadeCajaTexto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SalarioCajaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CorreoCajaTexto = new javax.swing.JTextField();
        ContraseñaCajaTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Boton_guardar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        Error7 = new javax.swing.JLabel();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        Error4 = new javax.swing.JLabel();
        Error5 = new javax.swing.JLabel();
        Error6 = new javax.swing.JLabel();
        BoxGenero = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablareportes = new javax.swing.JTable();
        IdLeavel = new javax.swing.JLabel();
        IdCajaTexto = new javax.swing.JTextField();
        Boton_Buscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Error = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 54, -1));

        NombreCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCajaTextoActionPerformed(evt);
            }
        });
        NombreCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreCajaTextoKeyTyped(evt);
            }
        });
        jPanel8.add(NombreCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 165, -1));

        DireccionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(DireccionCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 165, -1));

        jLabel2.setText("Direeccion");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, -1));

        TelefonoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoCajaTextoActionPerformed(evt);
            }
        });
        TelefonoCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoCajaTextoKeyTyped(evt);
            }
        });
        jPanel8.add(TelefonoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 165, -1));

        jLabel3.setText("Telefono");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 54, -1));

        EdadeCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadeCajaTextoActionPerformed(evt);
            }
        });
        EdadeCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EdadeCajaTextoKeyTyped(evt);
            }
        });
        jPanel8.add(EdadeCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 165, -1));

        jLabel4.setText("Salario");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 54, -1));

        SalarioCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioCajaTextoActionPerformed(evt);
            }
        });
        SalarioCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                SalarioCajaTextoKeyTyped(evt);
            }
        });
        jPanel8.add(SalarioCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 165, -1));

        jLabel5.setText("Genero");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 54, -1));

        jLabel6.setText("Edad");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 54, -1));

        jLabel7.setText("Contraseña");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 70, -1));

        CorreoCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(CorreoCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 165, -1));

        ContraseñaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(ContraseñaCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 165, -1));

        jLabel8.setText("Correo");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 54, -1));

        Boton_guardar.setText("Guardar");
        Boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardarActionPerformed(evt);
            }
        });
        jPanel8.add(Boton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jPanel8.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        Error7.setText("jLabel9");
        jPanel8.add(Error7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        Error1.setText("jLabel9");
        jPanel8.add(Error1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        Error2.setText("jLabel9");
        jPanel8.add(Error2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        Error3.setText("jLabel9");
        jPanel8.add(Error3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        Error4.setText("jLabel9");
        jPanel8.add(Error4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        Error5.setText("jLabel9");
        jPanel8.add(Error5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 20));

        Error6.setText("jLabel9");
        jPanel8.add(Error6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        BoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jPanel8.add(BoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 170, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablareportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Edad", "Direccion", "Genero", "Telefono", "Salario", "Correo", "Contraseña"
            }
        ));
        Tablareportes.setEnabled(false);
        Tablareportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablareportesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablareportes);
        ActualisarTabla();

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 700, 210));

        IdLeavel.setText("Id");
        jPanel1.add(IdLeavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        IdCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCajaTextoActionPerformed(evt);
            }
        });
        IdCajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdCajaTextoKeyTyped(evt);
            }
        });
        jPanel1.add(IdCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 110, -1));

        Boton_Buscar.setText("Buscar");
        Boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        Error.setText("jLabel9");
        jPanel1.add(Error, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 770, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCajaTextoActionPerformed

    private void DireccionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionCajaTextoActionPerformed

    private void TelefonoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoCajaTextoActionPerformed

    private void EdadeCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadeCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadeCajaTextoActionPerformed

    private void SalarioCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalarioCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalarioCajaTextoActionPerformed

    private void CorreoCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoCajaTextoActionPerformed

    private void ContraseñaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaCajaTextoActionPerformed

    private void Boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardarActionPerformed
        int a = Lectura.Ltext(NombreCajaTexto.getText())
                + Lectura.Lint(EdadeCajaTexto.getText())
                + Lectura.Ltext(DireccionCajaTexto.getText())
                + Lectura.Ltelefono(TelefonoCajaTexto.getText())
                + Lectura.Lcorreo(CorreoCajaTexto.getText(), "+(admin)+")
                + Lectura.LContraseña(ContraseñaCajaTexto.getText())
                + Lectura.LFloat(SalarioCajaTexto.getText());

        if (a == 7) {
            if (ComprobarExistencia()) {
                dao.createAdministrador(new Administrador(1,
                        NombreCajaTexto.getText(),
                        Integer.valueOf(EdadeCajaTexto.getText()),
                        DireccionCajaTexto.getText(),
                        String.valueOf(BoxGenero.getSelectedItem()),
                        TelefonoCajaTexto.getText(),
                        Float.valueOf(SalarioCajaTexto.getText()),
                        CorreoCajaTexto.getText(),
                        ContraseñaCajaTexto.getText()));
                LimpiarError();
                LimpiarCajas();
                ActualisarTabla();
            } else {
                Error.setText("El Correo ya esta en uso");
            }

        } else {
            if (Lectura.Ltext(NombreCajaTexto.getText()) != 1) {
                Error1.setText("!");
            } else {
                Error1.setText("");
            }
            if (Lectura.Ltext(DireccionCajaTexto.getText()) != 1) {
                Error2.setText("!");
            } else {
                Error2.setText("");
            }
            if (Lectura.Ltelefono(TelefonoCajaTexto.getText()) != 1) {
                Error3.setText("!");
            } else {
                Error3.setText("");
            }
            if (Lectura.Lcorreo(CorreoCajaTexto.getText(), "+(admin)+") != 1) {
                Error4.setText("!");
            } else {
                Error4.setText("");
            }
            if (Lectura.Lint(EdadeCajaTexto.getText()) != 1) {
                Error5.setText("!");
            } else {
                Error5.setText("");
            }
            if (Lectura.LFloat(SalarioCajaTexto.getText()) != 1) {
                Error6.setText("!");
            } else {
                Error6.setText("");
            }
            if (Lectura.LContraseña(ContraseñaCajaTexto.getText()) != 1) {
                Error7.setText("!");
            } else {
                Error7.setText("");
            }
        }
    }//GEN-LAST:event_Boton_guardarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        LimpiarCajas();
        LimpiarError();
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Lectura.Lint(IdCajaTexto.getText()) == 1 && IdCajaTexto.getText() != null) {
            if (JOptionPane.showConfirmDialog(null, "¿Desea eliminar el Administrador?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dao.deleteAdministrador(IdCajaTexto.getText());
                ActualisarTabla();
                LimpiarError();
                JOptionPane.showMessageDialog(null, "Se a eliminado el Administrador correctamente");
                Error.setText("");
            } else {
                LimpiarError();
                Error.setText("");
            }

        } else {
            Error.setText("Ingrese una id valida");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (Lectura.Lint(IdCajaTexto.getText()) == 1 && IdCajaTexto.getText() != null) {
            int a = Lectura.Ltext(NombreCajaTexto.getText())
                    + Lectura.Lint(EdadeCajaTexto.getText())
                    + Lectura.Ltext(DireccionCajaTexto.getText())
                    + Lectura.Ltelefono(TelefonoCajaTexto.getText())
                    + Lectura.Lcorreo(CorreoCajaTexto.getText(), "+(admin)+")
                    + Lectura.LContraseña(ContraseñaCajaTexto.getText())
                    + Lectura.LFloat(SalarioCajaTexto.getText());
            if (a == 7) {
                Administrador b = new Administrador(1,
                        NombreCajaTexto.getText(),
                        Integer.valueOf(EdadeCajaTexto.getText()),
                        DireccionCajaTexto.getText(),
                        String.valueOf(BoxGenero.getSelectedItem()),
                        TelefonoCajaTexto.getText(),
                        Float.valueOf(SalarioCajaTexto.getText()),
                        CorreoCajaTexto.getText(),
                        ContraseñaCajaTexto.getText());
                dao.updateAdministrador(b, IdCajaTexto.getText());
                LimpiarCajas();
                ActualisarTabla();
                Error.setText("");
            } else {
                if (Lectura.Ltext(NombreCajaTexto.getText()) != 1) {
                    Error1.setText("!");
                } else {
                    Error1.setText("");
                }
                if (Lectura.Ltext(DireccionCajaTexto.getText()) != 1) {
                    Error2.setText("!");
                } else {
                    Error2.setText("");
                }
                if (Lectura.Ltelefono(TelefonoCajaTexto.getText()) != 1) {
                    Error3.setText("!");
                } else {
                    Error3.setText("");
                }
                if (Lectura.Lcorreo(CorreoCajaTexto.getText(), "+(admin)+") != 1) {
                    Error4.setText("!");
                } else {
                    Error4.setText("");
                }
                if (Lectura.Lint(EdadeCajaTexto.getText()) != 1) {
                    Error5.setText("!");
                } else {
                    Error5.setText("");
                }
                if (Lectura.LFloat(SalarioCajaTexto.getText()) != 1) {
                    Error6.setText("!");
                } else {
                    Error6.setText("");
                }
                if (Lectura.LContraseña(ContraseñaCajaTexto.getText()) != 1) {
                    Error7.setText("!");
                } else {
                    Error7.setText("");
                }
            }
        } else {
            Error.setText("Ingrese una id valida");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TablareportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablareportesMouseClicked
        int filaSeleccionada = Tablareportes.rowAtPoint(evt.getPoint());
        IdCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 0).toString());
        NombreCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 1).toString());
        EdadeCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 2).toString());
        DireccionCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 3).toString());
        BoxGenero.setSelectedItem(Tablareportes.getValueAt(filaSeleccionada, 4).toString());
        TelefonoCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 5).toString());
        SalarioCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 6).toString());
        CorreoCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 7).toString());
        ContraseñaCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 8).toString());
    }//GEN-LAST:event_TablareportesMouseClicked

    private void IdCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCajaTextoActionPerformed

    private void Boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarActionPerformed
        if (IdCajaTexto.getText().isEmpty() || Lectura.Lint(IdCajaTexto.getText()) == 0) {
            Error.setText("Ingrese un valor valido");

        } else {
            Administrador gerente = dao.readAdministrador(IdCajaTexto.getText());
            if (gerente == null) {
                Error.setText("La id no existe");
            } else {
                NombreCajaTexto.setText(gerente.getNombre());
                EdadeCajaTexto.setText(String.valueOf(gerente.getEdad()));
                DireccionCajaTexto.setText(gerente.getDireccion());
                BoxGenero.setSelectedItem(gerente.getGenero());
                SalarioCajaTexto.setText(String.valueOf(gerente.getSalario()));
                TelefonoCajaTexto.setText(gerente.getTelefono());
                CorreoCajaTexto.setText(gerente.getCorreo());
                ContraseñaCajaTexto.setText(gerente.getContraseña());
            }

        }
    }//GEN-LAST:event_Boton_BuscarActionPerformed

    private void TelefonoCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoCajaTextoKeyTyped
        if (TelefonoCajaTexto.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoCajaTextoKeyTyped

    private void NombreCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreCajaTextoKeyTyped
        if (NombreCajaTexto.getText().length() >= 50) {
            evt.consume();
        }
    }//GEN-LAST:event_NombreCajaTextoKeyTyped

    private void EdadeCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EdadeCajaTextoKeyTyped
        if (EdadeCajaTexto.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_EdadeCajaTextoKeyTyped

    private void SalarioCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SalarioCajaTextoKeyTyped
        if (SalarioCajaTexto.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_SalarioCajaTextoKeyTyped

    private void IdCajaTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdCajaTextoKeyTyped
        if (IdCajaTexto.getText().length() >= 5) {
            evt.consume();
        }
    }//GEN-LAST:event_IdCajaTextoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Font segoeFont = new Font("Segoe UI", Font.PLAIN, 14);
        Font bookshelfFont = new Font("Bookshelf Symbol 7", Font.PLAIN, 14);

        Font currentFont = ContraseñaCajaTexto.getFont();

        if (currentFont.getName().equals("Segoe UI")) {
            ContraseñaCajaTexto.setFont(bookshelfFont);
        } else {
            ContraseñaCajaTexto.setFont(segoeFont);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Buscar;
    private javax.swing.JButton Boton_guardar;
    private javax.swing.JComboBox<String> BoxGenero;
    private javax.swing.JTextField ContraseñaCajaTexto;
    private javax.swing.JTextField CorreoCajaTexto;
    private javax.swing.JTextField DireccionCajaTexto;
    private javax.swing.JTextField EdadeCajaTexto;
    private javax.swing.JLabel Error;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JLabel Error4;
    private javax.swing.JLabel Error5;
    private javax.swing.JLabel Error6;
    private javax.swing.JLabel Error7;
    private javax.swing.JTextField IdCajaTexto;
    private javax.swing.JLabel IdLeavel;
    private javax.swing.JTextField NombreCajaTexto;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField SalarioCajaTexto;
    private javax.swing.JTable Tablareportes;
    private javax.swing.JTextField TelefonoCajaTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void ActualisarTabla() {

        ArrayList<Administrador> Administadores = dao.readAdministrador();

        DefaultTableModel m;
        m = (DefaultTableModel) Tablareportes.getModel();
        while (m.getRowCount() > 0) {
            m.removeRow(0);

        }
        Object[] rowData = new Object[9];
        for (int i = 0; i < Administadores.size(); i++) {
            rowData[0] = Administadores.get(i).getId();
            rowData[1] = Administadores.get(i).getNombre();
            rowData[2] = Administadores.get(i).getEdad();
            rowData[3] = Administadores.get(i).getDireccion();
            rowData[4] = Administadores.get(i).getGenero();
            rowData[5] = Administadores.get(i).getTelefono();
            rowData[6] = Administadores.get(i).getSalario();
            rowData[7] = Administadores.get(i).getCorreo();
            rowData[8] = Administadores.get(i).getContraseña();
            m.addRow(rowData);
        }
        Tablareportes.setModel(m);
    }

    private void LimpiarCajas() {
        NombreCajaTexto.setText("");
        EdadeCajaTexto.setText("");
        DireccionCajaTexto.setText("");
        TelefonoCajaTexto.setText("");
        SalarioCajaTexto.setText("");
        CorreoCajaTexto.setText("");
        ContraseñaCajaTexto.setText("");
        IdCajaTexto.setText("");
    }

    private void LimpiarError() {
        Error1.setText("");
        Error2.setText("");
        Error3.setText("");
        Error4.setText("");
        Error5.setText("");
        Error6.setText("");
        Error7.setText("");
    }

    private boolean ComprobarExistencia() {
        ArrayList<Administrador> Clientes = dao.readAdministrador();

        for (int i = 0; i < Clientes.size(); i++) {
            if (Clientes.get(i).getCorreo().equals(CorreoCajaTexto.getText())) {
                return false;
            }
        }
        return true;
    }

}
