/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventanas;

import Clases.Productos;
import dao.DaoProductos;
import dao.RenderImagen;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class PanelProductos extends javax.swing.JPanel {

    DaoProductos dao = new DaoProductos();
    String Ruta = null;

    public PanelProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreCajaTexto = new javax.swing.JTextField();
        CantidadCajaTexto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PrecioCajaTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MarcaCajaTexto = new javax.swing.JTextField();
        ColorCajaTexto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DescripcionCajaTexto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        OfertaCajaTexto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Boton_guardar = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Examinarboton = new javax.swing.JButton();
        Imagenleavel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablareportes = new javax.swing.JTable();
        IdLeavel = new javax.swing.JLabel();
        IdCajaTexto = new javax.swing.JTextField();
        Boton_Buscar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        jPanel8.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 54, -1));

        NombreCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(NombreCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 165, -1));

        CantidadCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(CantidadCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 165, -1));

        jLabel2.setText("Cantidad");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

        PrecioCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(PrecioCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 165, -1));

        jLabel3.setText("Preccio");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 54, -1));

        MarcaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(MarcaCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 165, -1));

        ColorCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(ColorCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 165, -1));

        jLabel4.setText("Descrpcion");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 80, -1));

        DescripcionCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripcionCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(DescripcionCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 165, -1));

        jLabel5.setText("Color");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 54, -1));

        jLabel6.setText("Marca");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 54, -1));

        jLabel7.setText("Oferta");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 70, -1));

        OfertaCajaTexto.setText("00");
        OfertaCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfertaCajaTextoActionPerformed(evt);
            }
        });
        jPanel8.add(OfertaCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 165, -1));

        jLabel8.setText("Imagen");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 54, -1));

        Boton_guardar.setText("Guardar");
        Boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_guardarActionPerformed(evt);
            }
        });
        jPanel8.add(Boton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        Nuevo.setText("Nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jPanel8.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        Examinarboton.setText("Examinar");
        Examinarboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExaminarbotonActionPerformed(evt);
            }
        });
        jPanel8.add(Examinarboton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 160, -1));
        jPanel8.add(Imagenleavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 110));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 350));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tablareportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Marca", "Cantidad", "Color", "Precio", "Descripccion", "Imangen", "Oferta"
            }
        ));
        Tablareportes.setEnabled(false);
        Tablareportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablareportesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablareportes);
        ActualisarTabla();

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 750, 290));

        IdLeavel.setText("Id");
        jPanel1.add(IdLeavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        IdCajaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdCajaTextoActionPerformed(evt);
            }
        });
        jPanel1.add(IdCajaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 110, -1));

        Boton_Buscar.setText("Buscar");
        Boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 770, 350));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreCajaTextoActionPerformed

    private void CantidadCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadCajaTextoActionPerformed

    private void PrecioCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioCajaTextoActionPerformed

    private void MarcaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaCajaTextoActionPerformed

    private void ColorCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColorCajaTextoActionPerformed

    private void DescripcionCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionCajaTextoActionPerformed

    private void OfertaCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OfertaCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OfertaCajaTextoActionPerformed

    private void Boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_guardarActionPerformed
        dao.createProducto(new Productos(1,
                NombreCajaTexto.getText(),
                MarcaCajaTexto.getText(),
                Integer.valueOf(CantidadCajaTexto.getText()),
                ColorCajaTexto.getText(),
                Float.valueOf(PrecioCajaTexto.getText()),
                DescripcionCajaTexto.getText(),
                getImagen(Ruta),
                Integer.valueOf(OfertaCajaTexto.getText())));

        LimpiarCajas();
        ActualisarTabla();
    }//GEN-LAST:event_Boton_guardarActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        LimpiarCajas();
    }//GEN-LAST:event_NuevoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dao.deleteProducto(IdCajaTexto.getText());
        ActualisarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Productos b = (new Productos(1,
                NombreCajaTexto.getText(),
                MarcaCajaTexto.getText(),
                Integer.valueOf(CantidadCajaTexto.getText()),
                ColorCajaTexto.getText(),
                Float.valueOf(PrecioCajaTexto.getText()),
                DescripcionCajaTexto.getText(),
                getImagen(Ruta),
                Integer.valueOf(OfertaCajaTexto.getText())));
        LimpiarCajas();
        ActualisarTabla();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TablareportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablareportesMouseClicked
        int filaSeleccionada = Tablareportes.rowAtPoint(evt.getPoint());
        IdCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 0).toString());
        NombreCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 1).toString());
        MarcaCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 2).toString());
        CantidadCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 3).toString());
        ColorCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 4).toString());
        PrecioCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 5).toString());
        DescripcionCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 6).toString());
        //Imagenleavel.setIcon(Tablareportes.getValueAt(filaSeleccionada, 7));
        Object valor = Tablareportes.getValueAt(filaSeleccionada, 7);
        Icon icono = ((JLabel) valor).getIcon();
        Imagenleavel.setIcon(icono);
        OfertaCajaTexto.setText(Tablareportes.getValueAt(filaSeleccionada, 8).toString());
    }//GEN-LAST:event_TablareportesMouseClicked

    private void IdCajaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdCajaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdCajaTextoActionPerformed

    private void Boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarActionPerformed
        Productos Producto = dao.readProducto(IdCajaTexto.getText());
        if (Producto == null) {
            System.out.println("la id no existe");

        } else {

            NombreCajaTexto.setText(Producto.getNombre());
            MarcaCajaTexto.setText(Producto.getMarca());
            CantidadCajaTexto.setText(String.valueOf(Producto.getCantidad()));
            ColorCajaTexto.setText(Producto.getColor());
            DescripcionCajaTexto.setText(String.valueOf(Producto.getDescripcion()));
            PrecioCajaTexto.setText(String.valueOf(Producto.getPrecio()));
            OfertaCajaTexto.setText(String.valueOf(Producto.getOferta()));

        }
    }//GEN-LAST:event_Boton_BuscarActionPerformed

    private void ExaminarbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExaminarbotonActionPerformed
        JFileChooser fileChoser = new JFileChooser();
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChoser.setFileFilter(extensionFilter);
        if (fileChoser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            Ruta = fileChoser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(Ruta).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(Imagenleavel.getWidth(), Imagenleavel.getHeight(), 0));
            Imagenleavel.setIcon(mIcono);
        }
    }//GEN-LAST:event_ExaminarbotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Buscar;
    private javax.swing.JButton Boton_guardar;
    private javax.swing.JTextField CantidadCajaTexto;
    private javax.swing.JTextField ColorCajaTexto;
    private javax.swing.JTextField DescripcionCajaTexto;
    private javax.swing.JButton Examinarboton;
    private javax.swing.JTextField IdCajaTexto;
    private javax.swing.JLabel IdLeavel;
    private javax.swing.JLabel Imagenleavel;
    private javax.swing.JTextField MarcaCajaTexto;
    private javax.swing.JTextField NombreCajaTexto;
    private javax.swing.JButton Nuevo;
    private javax.swing.JTextField OfertaCajaTexto;
    private javax.swing.JTextField PrecioCajaTexto;
    private javax.swing.JTable Tablareportes;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
private void ActualisarTabla() {
        Tablareportes.setDefaultRenderer(Object.class, new RenderImagen());
        ArrayList<Productos> Productos = dao.readProductos();

        DefaultTableModel m;
        m = (DefaultTableModel) Tablareportes.getModel();
        while (m.getRowCount() > 0) {
            m.removeRow(0);

        }
        Object[] rowData = new Object[9];
        for (int i = 0; i < Productos.size(); i++) {
            rowData[0] = Productos.get(i).getId();
            rowData[1] = Productos.get(i).getNombre();
            rowData[2] = Productos.get(i).getMarca();
            rowData[3] = Productos.get(i).getCantidad();
            rowData[4] = Productos.get(i).getColor();
            rowData[5] = Productos.get(i).getPrecio();
            rowData[6] = Productos.get(i).getDescripcion();
            try {
                byte[] imagen = Productos.get(i).getImagen();
                BufferedImage bufferedImage = null;
                InputStream inputStream = new ByteArrayInputStream(imagen);
                bufferedImage = ImageIO.read(inputStream);
                ImageIcon mIcono = new ImageIcon(bufferedImage.getScaledInstance(150, 110, 0));
                rowData[7] = new JLabel(mIcono);
            } catch (Exception e) {
                rowData[7] = new JLabel("no imagen");
            }
            rowData[8] = Productos.get(i).getOferta();
            m.addRow(rowData);
        }
        Tablareportes.setModel(m);
        Tablareportes.setRowHeight(110);
        Tablareportes.getColumnModel().getColumn(7).setPreferredWidth(150);
    }

    private void LimpiarCajas() {
        IdCajaTexto.setText("");
        NombreCajaTexto.setText("");
        MarcaCajaTexto.setText("");
        CantidadCajaTexto.setText("");
        ColorCajaTexto.setText("");
        PrecioCajaTexto.setText("");
        DescripcionCajaTexto.setText("");
        OfertaCajaTexto.setText("");
        IdCajaTexto.setText("");
        Imagenleavel.setText("");
        Ruta = null;

    }

    private byte[] getImagen(String Ruta) {
        File imagen = new File(Ruta);
        try {
            byte[] icono = new byte[(int) imagen.length()];
            InputStream input = new FileInputStream(imagen);
            input.read(icono);
            return icono;
        } catch (Exception ex) {
            return null;
        }

    }

}
